#!/usr/bin/env bash

set +o errexit
set +o nounset

default_variables() {
  ROOT_DIR=$(git rev-parse --show-toplevel) || exit 1
  VERSION="0.0.1"

  last_version=$(git describe --abbrev=0 --tags)
  next_version=

  signed=

  declare -A types 2>/dev/null || exit_err "Bash version not supported (requires 4)"
  types[feat]="Features"
  types[fix]="Bug Fixes"
  types[perf]="Performance Improvements"
}

# exit with message to stderr
exit_err() {
  echo "$@" >&2
  exit 1
}

has_cmd() {
  command -v $1 >/dev/null 2>&1
}

# exit if command isn't available
depend() {
  has_cmd $1 || exit_err "Missing dependency: $1"
}

calculate_version() {

}

bump_git() {

}

bump_npm() {
  has_cmd npm || return
  [[ -f "$(npm prefix)/package.json"]] || return
  npm version --no-git-tag-version "$VERSION"
}

depend git
